services:
  mongo:
    image: mongo:8.0.13
    container_name: formio-db
    restart: unless-stopped
    ports:
      - "3011:27017"
    volumes:
      - "formio_data_db:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - formio
  formio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formio
    restart: unless-stopped
    ports:
      - "8011:3001"
    environment:
      DEBUG: formio:*
      ROOT_EMAIL: admin@cmfitzroy.com.ar
      ROOT_PASSWORD: fitzsecret321
      API_KEYS: clave01
      NODE_CONFIG: |
        {
          "mongo": "mongodb://formio-db:27017/formio-ce?replicaSet=rs0",
          "port": 3001,
          "jwt": {
            "secret": "fitzsecret321"
          }
        }
    networks:
      - formio
    depends_on:
      - mongo-init
  mongo-init:
    image: mongo:8.0.13
    container_name: mongo-init
    depends_on:
      - mongo
    networks:
      - formio
    entrypoint: >
      bash -c "
        echo 'Esperando a Mongo...';
        until mongosh --host mongo:27017 --eval 'db.adminCommand({ping:1})' >/dev/null 2>&1; do
          sleep 1;
        done;
        echo 'Inicializando ReplicaSet...';
        mongosh --host mongo:27017 --eval '
          try {
            rs.status()
          } catch(e) {
            rs.initiate({
              _id: \"rs0\",
              members: [{ _id: 0, host: \"mongo:27017\" }]
            })
          }'
      "
  audit:
    container_name: mongo-audit
    build: ./audit
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/formio-ce
    depends_on:
      - mongo-init
    networks:
      - formio
networks:
  formio:
    driver: bridge
    
volumes:
  formio_data_db:
