services:
  mongo:
    image: mongo:8.0.13
    container_name: formio-db
    restart: unless-stopped
    ports:
      - "3011:27017"
    volumes:
      - "formio_data_db:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    networks:
      - formio
  formio:
    image: ghcr.io/cmifr-devops/formio-formio:v4.6.0-rc.3
    container_name: formio
    restart: unless-stopped
    ports:
      - "8011:3001"
    environment:
      DEBUG: formio:*
      ROOT_EMAIL: admin@cmfitzroy.com.ar
      ROOT_PASSWORD: fitzsecret321
      NODE_CONFIG: |
        {
          "mongo": "mongodb://formio-db:27017/formio-ce",
          "port": 3001,
          "jwt": {
            "secret": "fitzsecret321"
          }
        }
    networks:
      - formio
    depends_on:
      - mongo
networks:
  formio:
    driver: bridge
    
volumes:
  formio_data_db:
